# **M√≥dulo 2. Plataformas de Aplicaci√≥n sobre Python**
**Pr√°ctica 1 - An√°lisis de Tweets de la vacunaci√≥n**
---

In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

Leer el archivo vaccination_tweets.csv y dejarlo en un dataframe

In [ ]:
tweets = pd.read_csv('/content/vaccination_tweets.csv')
tweets.head()

             id             user_name  ... favorites is_retweet
0  1.340000e+18            Rachel Roh  ...         0      False
1  1.340000e+18           Albert Fong  ...         1      False
2  1.340000e+18              eliüá±üáπüá™üá∫üëå  ...         0      False
3  1.340000e+18         Charles Adler  ...      2129      False
4  1.340000e+18  Citizen News Channel  ...         0      False

[5 rows x 16 columns]

Los 5 usuarios con m√°s seguidores

In [ ]:
masSeguidores = tweets[['user_name', 'user_followers']]
masSeguidores = masSeguidores.sort_values('user_followers')
masSeguidores = masSeguidores.drop_duplicates(subset='user_name')
masSeguidores[:-6:-1]

       user_name  user_followers
1121        CGTN        13714928
2113    ABP News        10741934
912    The Hindu         6565800
1481  IndiaToday         5450165
293      DD News         3085027

La cantidad promedio de amigos que tienen los usuarios

In [ ]:
tweets['user_friends'].mean()

1156.2060747663552

La cantidad de usuarios por cada fuente de donde hicieron el tweet

In [ ]:
tweets[['source', 'user_name']].groupby('source').count()

                                 user_name
source
24liveblog                               4
Blog2Social APP                          1
Buffer                                  36
EastMojo                                 1
Echobox                                  2
Falcon Social Media Management           2
GT_Backend                               2
Hootsuite Inc.                          16
IFTTT                                    3
Instagram                               24
LinkedIn                                 5
Microsoft Power Platform                 5
News Users                               1
Nonli                                    6
Paper.li                                 1
Publer                                   1
Sendible                                 2
SocialFlow                               5
SocialNewsDesk                           1
Socialbakers                             1
Sprout Social                            1
ThreadReaderApp                          1
TweetCaster for Android                  1
TweetDeck                              240
Tweetbot for Mac                         1
Twitter Media Studio                     2
Twitter Media Studio - LiveCut           1
Twitter Web App                       1271
Twitter for Android                    999
Twitter for Mac                          3
Twitter for iPad                       112
Twitter for iPhone                    1526
UberSocial for Android                   1
WordPress.com                            1

El promedio de retweets, sin considerar a aquellos usuarios que no tienen retweetts

In [ ]:
retweets = tweets[tweets['retweets']>0]
retweets['retweets'].mean()

5.893939393939394

Los 5 primeros usuarios que tienen m√°s de 100 favoritos

In [ ]:
fav100 = tweets[tweets['favorites']>100]
fav100 = fav100[['user_name', 'favorites']]
fav100.sort_values('favorites', ascending=True, inplace=True)
fav100[:5:]

                   user_name  favorites
2746  Krutika Nitin Mediwala        102
2918          eimearmccarthy        104
3607   Jackson Health System        110
350             Taz Ebenezer        112
1985         Suzanne Devkota        114